// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_stats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetPlatformStats = `-- name: AdminGetPlatformStats :one
SELECT
    (SELECT COUNT(*) FROM "users") AS total_users,
    (SELECT COUNT(*) FROM "users" WHERE "role" = 'ORGANISER') AS total_organisers,
    (SELECT COUNT(*) FROM "users" WHERE "role" = 'ATTENDEE') AS total_attendees,
    (SELECT COUNT(*) FROM "events") AS total_events,
    (SELECT COUNT(*) FROM "events" WHERE "status" = 'PUBLISHED') AS published_events,
    (SELECT COUNT(*) FROM "orders") AS total_orders,
    (SELECT COUNT(*) FROM "orders" WHERE "status" = 'PAID') AS paid_orders,
    (SELECT COALESCE(SUM("total_amount"), 0) FROM "orders" WHERE "status" = 'PAID') AS total_revenue
`

type AdminGetPlatformStatsRow struct {
	TotalUsers      int64
	TotalOrganisers int64
	TotalAttendees  int64
	TotalEvents     int64
	PublishedEvents int64
	TotalOrders     int64
	PaidOrders      int64
	TotalRevenue    interface{}
}

func (q *Queries) AdminGetPlatformStats(ctx context.Context) (AdminGetPlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetPlatformStats)
	var i AdminGetPlatformStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalOrganisers,
		&i.TotalAttendees,
		&i.TotalEvents,
		&i.PublishedEvents,
		&i.TotalOrders,
		&i.PaidOrders,
		&i.TotalRevenue,
	)
	return i, err
}

const adminGetRecentOrdersWithDetails = `-- name: AdminGetRecentOrdersWithDetails :many
SELECT
    o.id, o.user_id, o.event_id, o.ticket_type_id, o.quantity, o.unit_price, o.total_amount, o.currency, o.status, o.payment_method, o.payment_ref, o.qr_code, o.checked_in, o.checked_in_at, o.created_at, o.updated_at,
    u."name"  AS user_name,
    u."email" AS user_email,
    e."title" AS event_title
FROM "orders" o
JOIN "users"  u ON u."id" = o."user_id"
JOIN "events" e ON e."id" = o."event_id"
ORDER BY o."created_at" DESC
LIMIT $1
`

type AdminGetRecentOrdersWithDetailsRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	EventID       pgtype.UUID
	TicketTypeID  pgtype.UUID
	Quantity      int32
	UnitPrice     pgtype.Numeric
	TotalAmount   pgtype.Numeric
	Currency      string
	Status        OrderStatus
	PaymentMethod NullPaymentMethod
	PaymentRef    pgtype.Text
	QrCode        pgtype.Text
	CheckedIn     bool
	CheckedInAt   pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	UserName      string
	UserEmail     string
	EventTitle    string
}

func (q *Queries) AdminGetRecentOrdersWithDetails(ctx context.Context, limit int32) ([]AdminGetRecentOrdersWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, adminGetRecentOrdersWithDetails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetRecentOrdersWithDetailsRow
	for rows.Next() {
		var i AdminGetRecentOrdersWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.EventTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetTotalRevenue = `-- name: AdminGetTotalRevenue :one
SELECT COALESCE(SUM("total_amount"), 0)::BIGINT AS total_revenue
FROM "orders"
WHERE "status" = 'PAID'
`

func (q *Queries) AdminGetTotalRevenue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminGetTotalRevenue)
	var total_revenue int64
	err := row.Scan(&total_revenue)
	return total_revenue, err
}
