// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_stats.sql

package repository

import (
	"context"
)

const adminGetPlatformStats = `-- name: AdminGetPlatformStats :one
SELECT
    (SELECT COUNT(*) FROM "users") AS total_users,
    (SELECT COUNT(*) FROM "users" WHERE "role" = 'ORGANISER') AS total_organisers,
    (SELECT COUNT(*) FROM "users" WHERE "role" = 'ATTENDEE') AS total_attendees,
    (SELECT COUNT(*) FROM "events") AS total_events,
    (SELECT COUNT(*) FROM "events" WHERE "status" = 'PUBLISHED') AS published_events,
    (SELECT COUNT(*) FROM "orders") AS total_orders,
    (SELECT COUNT(*) FROM "orders" WHERE "status" = 'PAID') AS paid_orders,
    (SELECT COALESCE(SUM("total_amount"), 0) FROM "orders" WHERE "status" = 'PAID') AS total_revenue
`

type AdminGetPlatformStatsRow struct {
	TotalUsers      int64
	TotalOrganisers int64
	TotalAttendees  int64
	TotalEvents     int64
	PublishedEvents int64
	TotalOrders     int64
	PaidOrders      int64
	TotalRevenue    interface{}
}

func (q *Queries) AdminGetPlatformStats(ctx context.Context) (AdminGetPlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetPlatformStats)
	var i AdminGetPlatformStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalOrganisers,
		&i.TotalAttendees,
		&i.TotalEvents,
		&i.PublishedEvents,
		&i.TotalOrders,
		&i.PaidOrders,
		&i.TotalRevenue,
	)
	return i, err
}

const adminGetTotalRevenue = `-- name: AdminGetTotalRevenue :one
SELECT COALESCE(SUM("total_amount"), 0)::BIGINT AS total_revenue
FROM "orders"
WHERE "status" = 'PAID'
`

func (q *Queries) AdminGetTotalRevenue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminGetTotalRevenue)
	var total_revenue int64
	err := row.Scan(&total_revenue)
	return total_revenue, err
}
