// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCancelEvent = `-- name: AdminCancelEvent :one
UPDATE "events"
SET
    "status"     = 'CANCELLED',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at
`

func (q *Queries) AdminCancelEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, adminCancelEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteEvent = `-- name: AdminDeleteEvent :exec
UPDATE "events"
SET
    "status"     = 'DELETED',
    "updated_at" = NOW()
WHERE "id" = $1
`

func (q *Queries) AdminDeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteEvent, id)
	return err
}

const adminGetAllEvents = `-- name: AdminGetAllEvents :many
SELECT
    e.id, e.organiser_id, e.title, e.slug, e.description, e.location, e.venue, e.banner_url, e.starts_at, e.ends_at, e.status, e.is_online, e.online_url, e.created_at, e.updated_at,
    u."name" AS organiser_name
FROM "events" e
JOIN "users"  u ON u."id" = e."organiser_id"
ORDER BY e."created_at" DESC
LIMIT $1 OFFSET $2
`

type AdminGetAllEventsParams struct {
	Limit  int32
	Offset int32
}

type AdminGetAllEventsRow struct {
	ID            pgtype.UUID
	OrganiserID   pgtype.UUID
	Title         string
	Slug          string
	Description   pgtype.Text
	Location      pgtype.Text
	Venue         pgtype.Text
	BannerUrl     pgtype.Text
	StartsAt      pgtype.Timestamp
	EndsAt        pgtype.Timestamp
	Status        EventStatus
	IsOnline      bool
	OnlineUrl     pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	OrganiserName string
}

func (q *Queries) AdminGetAllEvents(ctx context.Context, arg AdminGetAllEventsParams) ([]AdminGetAllEventsRow, error) {
	rows, err := q.db.Query(ctx, adminGetAllEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetAllEventsRow
	for rows.Next() {
		var i AdminGetAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.Venue,
			&i.BannerUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganiserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetEventsByStatus = `-- name: AdminGetEventsByStatus :many
SELECT
    e.id, e.organiser_id, e.title, e.slug, e.description, e.location, e.venue, e.banner_url, e.starts_at, e.ends_at, e.status, e.is_online, e.online_url, e.created_at, e.updated_at,
    u."name" AS organiser_name
FROM "events" e
JOIN "users"  u ON u."id" = e."organiser_id"
WHERE e."status" = $1
ORDER BY e."created_at" DESC
LIMIT $2 OFFSET $3
`

type AdminGetEventsByStatusParams struct {
	Status EventStatus
	Limit  int32
	Offset int32
}

type AdminGetEventsByStatusRow struct {
	ID            pgtype.UUID
	OrganiserID   pgtype.UUID
	Title         string
	Slug          string
	Description   pgtype.Text
	Location      pgtype.Text
	Venue         pgtype.Text
	BannerUrl     pgtype.Text
	StartsAt      pgtype.Timestamp
	EndsAt        pgtype.Timestamp
	Status        EventStatus
	IsOnline      bool
	OnlineUrl     pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	OrganiserName string
}

func (q *Queries) AdminGetEventsByStatus(ctx context.Context, arg AdminGetEventsByStatusParams) ([]AdminGetEventsByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminGetEventsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetEventsByStatusRow
	for rows.Next() {
		var i AdminGetEventsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.Venue,
			&i.BannerUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganiserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
