// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminBanUser = `-- name: AdminBanUser :one
UPDATE "users"
SET
    "status"  = 'BANNED',
    "banned_at"  = NOW(),
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

func (q *Queries) AdminBanUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, adminBanUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteUser = `-- name: AdminDeleteUser :one
UPDATE "users"
SET
    "status"     = 'DELETED',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

func (q *Queries) AdminDeleteUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, adminDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetAllUsers = `-- name: AdminGetAllUsers :many
SELECT id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at FROM "users"
ORDER BY "created_at" DESC
LIMIT $1 OFFSET $2
`

type AdminGetAllUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) AdminGetAllUsers(ctx context.Context, arg AdminGetAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, adminGetAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.Status,
			&i.AvatarUrl,
			&i.BannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetApprovedOrganisers = `-- name: AdminGetApprovedOrganisers :many
SELECT id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at FROM "users"
WHERE "role" = 'ORGANISER'
AND "is_verified" = TRUE
AND "status" = 'ACTIVE'
ORDER BY "created_at" DESC
`

func (q *Queries) AdminGetApprovedOrganisers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, adminGetApprovedOrganisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.Status,
			&i.AvatarUrl,
			&i.BannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetPendingOrganisers = `-- name: AdminGetPendingOrganisers :many
SELECT id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at FROM "users"
WHERE "role" = 'ORGANISER'
AND "is_verified" = FALSE
ORDER BY "created_at" ASC
`

func (q *Queries) AdminGetPendingOrganisers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, adminGetPendingOrganisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.Status,
			&i.AvatarUrl,
			&i.BannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetUsersByRole = `-- name: AdminGetUsersByRole :many
SELECT id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at FROM "users"
WHERE "role" = $1
ORDER BY "created_at" DESC
LIMIT $2 OFFSET $3
`

type AdminGetUsersByRoleParams struct {
	Role   UserRole
	Limit  int32
	Offset int32
}

func (q *Queries) AdminGetUsersByRole(ctx context.Context, arg AdminGetUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, adminGetUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.Status,
			&i.AvatarUrl,
			&i.BannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetUsersByStatus = `-- name: AdminGetUsersByStatus :many
SELECT id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at FROM "users"
WHERE "status" = $1
ORDER BY "created_at" DESC
LIMIT $2 OFFSET $3
`

type AdminGetUsersByStatusParams struct {
	Status UserStatus
	Limit  int32
	Offset int32
}

func (q *Queries) AdminGetUsersByStatus(ctx context.Context, arg AdminGetUsersByStatusParams) ([]User, error) {
	rows, err := q.db.Query(ctx, adminGetUsersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.Status,
			&i.AvatarUrl,
			&i.BannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserRoleToAdmin = `-- name: AdminSetUserRoleToAdmin :one
UPDATE "users"
SET
    "role"       = 'ADMIN',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

func (q *Queries) AdminSetUserRoleToAdmin(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, adminSetUserRoleToAdmin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUnbanUser = `-- name: AdminUnbanUser :one
UPDATE "users"
SET
    "status"  = 'ACTIVE',
    "banned_at"  = NULL,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

func (q *Queries) AdminUnbanUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, adminUnbanUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdateUserVerification = `-- name: AdminUpdateUserVerification :one
UPDATE "users"
SET
    "is_verified" = $2,
    "updated_at"  = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

type AdminUpdateUserVerificationParams struct {
	ID         pgtype.UUID
	IsVerified bool
}

func (q *Queries) AdminUpdateUserVerification(ctx context.Context, arg AdminUpdateUserVerificationParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUserVerification, arg.ID, arg.IsVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
