// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCancelEvent = `-- name: AdminCancelEvent :one
UPDATE "events"
SET
    "status"     = 'CANCELLED',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at
`

func (q *Queries) AdminCancelEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, adminCancelEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteEvent = `-- name: AdminDeleteEvent :exec
DELETE FROM "events" WHERE "id" = $1
`

func (q *Queries) AdminDeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteEvent, id)
	return err
}

const adminDeleteUser = `-- name: AdminDeleteUser :exec
DELETE FROM "users" WHERE "id" = $1
`

func (q *Queries) AdminDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteUser, id)
	return err
}

const adminGetAllEvents = `-- name: AdminGetAllEvents :many
SELECT
    e.id, e.organiser_id, e.title, e.slug, e.description, e.location, e.venue, e.banner_url, e.starts_at, e.ends_at, e.status, e.is_online, e.online_url, e.created_at, e.updated_at,
    u."name" AS organiser_name
FROM "events" e
JOIN "users"  u ON u."id" = e."organiser_id"
ORDER BY e."created_at" DESC
LIMIT $1 OFFSET $2
`

type AdminGetAllEventsParams struct {
	Limit  int32
	Offset int32
}

type AdminGetAllEventsRow struct {
	ID            pgtype.UUID
	OrganiserID   pgtype.UUID
	Title         string
	Slug          string
	Description   pgtype.Text
	Location      pgtype.Text
	Venue         pgtype.Text
	BannerUrl     pgtype.Text
	StartsAt      pgtype.Timestamp
	EndsAt        pgtype.Timestamp
	Status        EventStatus
	IsOnline      bool
	OnlineUrl     pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	OrganiserName string
}

func (q *Queries) AdminGetAllEvents(ctx context.Context, arg AdminGetAllEventsParams) ([]AdminGetAllEventsRow, error) {
	rows, err := q.db.Query(ctx, adminGetAllEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetAllEventsRow
	for rows.Next() {
		var i AdminGetAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.Venue,
			&i.BannerUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganiserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetEventsByStatus = `-- name: AdminGetEventsByStatus :many
SELECT
    e.id, e.organiser_id, e.title, e.slug, e.description, e.location, e.venue, e.banner_url, e.starts_at, e.ends_at, e.status, e.is_online, e.online_url, e.created_at, e.updated_at,
    u."name" AS organiser_name
FROM "events" e
JOIN "users"  u ON u."id" = e."organiser_id"
WHERE e."status" = $1
ORDER BY e."created_at" DESC
LIMIT $2 OFFSET $3
`

type AdminGetEventsByStatusParams struct {
	Status EventStatus
	Limit  int32
	Offset int32
}

type AdminGetEventsByStatusRow struct {
	ID            pgtype.UUID
	OrganiserID   pgtype.UUID
	Title         string
	Slug          string
	Description   pgtype.Text
	Location      pgtype.Text
	Venue         pgtype.Text
	BannerUrl     pgtype.Text
	StartsAt      pgtype.Timestamp
	EndsAt        pgtype.Timestamp
	Status        EventStatus
	IsOnline      bool
	OnlineUrl     pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	OrganiserName string
}

func (q *Queries) AdminGetEventsByStatus(ctx context.Context, arg AdminGetEventsByStatusParams) ([]AdminGetEventsByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminGetEventsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetEventsByStatusRow
	for rows.Next() {
		var i AdminGetEventsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.Venue,
			&i.BannerUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganiserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetLatestOrders = `-- name: AdminGetLatestOrders :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
ORDER BY "created_at" DESC
LIMIT $1
`

func (q *Queries) AdminGetLatestOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, adminGetLatestOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetOrdersByStatus = `-- name: AdminGetOrdersByStatus :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "status" = $1
ORDER BY "created_at" DESC
LIMIT $2 OFFSET $3
`

type AdminGetOrdersByStatusParams struct {
	Status OrderStatus
	Limit  int32
	Offset int32
}

func (q *Queries) AdminGetOrdersByStatus(ctx context.Context, arg AdminGetOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, adminGetOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetPlatformStats = `-- name: AdminGetPlatformStats :one
SELECT
    (SELECT COUNT(*) FROM "users") AS total_users,
    (SELECT COUNT(*) FROM "users" WHERE "role" = 'ORGANISER') AS total_organisers,
    (SELECT COUNT(*) FROM "users" WHERE "role" = 'ATTENDEE') AS total_attendees,
    (SELECT COUNT(*) FROM "events") AS total_events,
    (SELECT COUNT(*) FROM "events" WHERE "status" = 'PUBLISHED') AS published_events,
    (SELECT COUNT(*) FROM "orders") AS total_orders,
    (SELECT COUNT(*) FROM "orders" WHERE "status" = 'PAID') AS paid_orders,
    (SELECT COALESCE(SUM("total_amount"), 0) FROM "orders" WHERE "status" = 'PAID') AS total_revenue
`

type AdminGetPlatformStatsRow struct {
	TotalUsers      int64
	TotalOrganisers int64
	TotalAttendees  int64
	TotalEvents     int64
	PublishedEvents int64
	TotalOrders     int64
	PaidOrders      int64
	TotalRevenue    interface{}
}

func (q *Queries) AdminGetPlatformStats(ctx context.Context) (AdminGetPlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetPlatformStats)
	var i AdminGetPlatformStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalOrganisers,
		&i.TotalAttendees,
		&i.TotalEvents,
		&i.PublishedEvents,
		&i.TotalOrders,
		&i.PaidOrders,
		&i.TotalRevenue,
	)
	return i, err
}

const adminGetRecentOrdersWithDetails = `-- name: AdminGetRecentOrdersWithDetails :many
SELECT
    o.id, o.user_id, o.event_id, o.ticket_type_id, o.quantity, o.unit_price, o.total_amount, o.currency, o.status, o.payment_method, o.payment_ref, o.qr_code, o.checked_in, o.checked_in_at, o.created_at, o.updated_at,
    u."name"  AS user_name,
    u."email" AS user_email,
    e."title" AS event_title
FROM "orders" o
JOIN "users"  u ON u."id" = o."user_id"
JOIN "events" e ON e."id" = o."event_id"
ORDER BY o."created_at" DESC
LIMIT $1
`

type AdminGetRecentOrdersWithDetailsRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	EventID       pgtype.UUID
	TicketTypeID  pgtype.UUID
	Quantity      int32
	UnitPrice     pgtype.Numeric
	TotalAmount   pgtype.Numeric
	Currency      string
	Status        OrderStatus
	PaymentMethod NullPaymentMethod
	PaymentRef    pgtype.Text
	QrCode        pgtype.Text
	CheckedIn     bool
	CheckedInAt   pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	UserName      string
	UserEmail     string
	EventTitle    string
}

func (q *Queries) AdminGetRecentOrdersWithDetails(ctx context.Context, limit int32) ([]AdminGetRecentOrdersWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, adminGetRecentOrdersWithDetails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetRecentOrdersWithDetailsRow
	for rows.Next() {
		var i AdminGetRecentOrdersWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.EventTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetTotalRevenue = `-- name: AdminGetTotalRevenue :one
SELECT COALESCE(SUM("total_amount"), 0) AS total_revenue
FROM "orders"
WHERE "status" = 'PAID'
`

func (q *Queries) AdminGetTotalRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, adminGetTotalRevenue)
	var total_revenue interface{}
	err := row.Scan(&total_revenue)
	return total_revenue, err
}

const banUser = `-- name: BanUser :one
UPDATE "users"
SET
    "is_banned"  = TRUE,
    "ban_reason" = $2,
    "banned_at"  = NOW(),
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at
`

type BanUserParams struct {
	ID        pgtype.UUID
	BanReason pgtype.Text
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) (User, error) {
	row := q.db.QueryRow(ctx, banUser, arg.ID, arg.BanReason)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.BannedAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at FROM "users"
ORDER BY "created_at" DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.IsBanned,
			&i.BanReason,
			&i.BannedAt,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApprovedOrganisers = `-- name: GetApprovedOrganisers :many
SELECT id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at FROM "users"
WHERE "role" = 'ORGANISER'
AND "is_verified" = TRUE
AND "is_banned" = FALSE
ORDER BY "created_at" DESC
`

func (q *Queries) GetApprovedOrganisers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getApprovedOrganisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.IsBanned,
			&i.BanReason,
			&i.BannedAt,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBannedUsers = `-- name: GetBannedUsers :many
SELECT id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at FROM "users"
WHERE "is_banned" = TRUE
ORDER BY "banned_at" DESC
`

func (q *Queries) GetBannedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getBannedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.IsBanned,
			&i.BanReason,
			&i.BannedAt,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOrganisers = `-- name: GetPendingOrganisers :many
SELECT id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at FROM "users"
WHERE "role" = 'ORGANISER'
AND "is_verified" = FALSE
ORDER BY "created_at" ASC
`

func (q *Queries) GetPendingOrganisers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getPendingOrganisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.IsBanned,
			&i.BanReason,
			&i.BannedAt,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at FROM "users"
WHERE "role" = $1
ORDER BY "created_at" DESC
LIMIT $2 OFFSET $3
`

type GetUsersByRoleParams struct {
	Role   UserRole
	Limit  int32
	Offset int32
}

func (q *Queries) GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsVerified,
			&i.IsBanned,
			&i.BanReason,
			&i.BannedAt,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteToAdmin = `-- name: PromoteToAdmin :one
UPDATE "users"
SET
    "role"       = 'ADMIN',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at
`

func (q *Queries) PromoteToAdmin(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, promoteToAdmin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.BannedAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unbanUser = `-- name: UnbanUser :one
UPDATE "users"
SET
    "is_banned"  = FALSE,
    "ban_reason" = NULL,
    "banned_at"  = NULL,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at
`

func (q *Queries) UnbanUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, unbanUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.BannedAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE "users"
SET
    "is_verified" = $2,
    "updated_at"  = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, is_banned, ban_reason, banned_at, avatar_url, created_at, updated_at
`

type UpdateUserVerificationParams struct {
	ID         pgtype.UUID
	IsVerified bool
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserVerification, arg.ID, arg.IsVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.BannedAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
