// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_orders.sql

package repository

import (
	"context"
)

const adminGetLatestOrders = `-- name: AdminGetLatestOrders :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
ORDER BY "created_at" DESC
LIMIT $1
`

func (q *Queries) AdminGetLatestOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, adminGetLatestOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetOrdersByStatus = `-- name: AdminGetOrdersByStatus :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "status" = $1
ORDER BY "created_at" DESC
LIMIT $2 OFFSET $3
`

type AdminGetOrdersByStatusParams struct {
	Status OrderStatus
	Limit  int32
	Offset int32
}

func (q *Queries) AdminGetOrdersByStatus(ctx context.Context, arg AdminGetOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, adminGetOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
