// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkin.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInOrder = `-- name: CheckInOrder :one
UPDATE "orders"
SET
    "checked_in"    = TRUE,
    "checked_in_at" = NOW(),
    "updated_at"    = NOW()
WHERE "id" = $1
AND "checked_in" = FALSE
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

func (q *Queries) CheckInOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, checkInOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckedInOrders = `-- name: GetCheckedInOrders :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "event_id" = $1
AND "checked_in" = TRUE
ORDER BY "checked_in_at" ASC
`

func (q *Queries) GetCheckedInOrders(ctx context.Context, eventID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getCheckedInOrders, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByQRCode = `-- name: GetOrderByQRCode :one
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "qr_code" = $1
`

func (q *Queries) GetOrderByQRCode(ctx context.Context, qrCode pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByQRCode, qrCode)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
