// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_categories.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO "event_categories" (
    "name",
    "description"
) VALUES (
    $1, $2
) RETURNING id, name, description, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (EventCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Description)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM "event_categories" WHERE "id" = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, description, created_at, updated_at FROM "event_categories"
ORDER BY "name" ASC
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]EventCategory, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategory
	for rows.Next() {
		var i EventCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, description, created_at, updated_at FROM "event_categories"
WHERE "id" = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (EventCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, description, created_at, updated_at FROM "event_categories"
WHERE "name" = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (EventCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE "event_categories"
SET
    "name"        = $2,
    "description" = $3,
    "updated_at"  = NOW()
WHERE "id" = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (EventCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Description)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
