// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events_organiser.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventsByOrganiser = `-- name: GetEventsByOrganiser :many
SELECT id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at FROM "events" 
WHERE "organiser_id" = $1
ORDER BY "created_at" DESC
`

func (q *Queries) GetEventsByOrganiser(ctx context.Context, organiserID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByOrganiser, organiserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.Venue,
			&i.BannerUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventStatus = `-- name: UpdateEventStatus :one
UPDATE "events"
SET
    "status"     = $2,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at
`

type UpdateEventStatusParams struct {
	ID     pgtype.UUID
	Status EventStatus
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventStatus, arg.ID, arg.Status)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
