// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEvent = `-- name: CancelEvent :one
UPDATE "events"
SET
    "status"     = 'CANCELLED',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at
`

func (q *Queries) CancelEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, cancelEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO "events" (
    "organiser_id",
    "title",
    "slug",
    "description",
    "location",
    "venue",
    "banner_url",
    "starts_at",
    "ends_at",
    "status",
    "is_online",
    "online_url"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at
`

type CreateEventParams struct {
	OrganiserID pgtype.UUID
	Title       string
	Slug        string
	Description pgtype.Text
	Location    pgtype.Text
	Venue       pgtype.Text
	BannerUrl   pgtype.Text
	StartsAt    pgtype.Timestamp
	EndsAt      pgtype.Timestamp
	Status      EventStatus
	IsOnline    bool
	OnlineUrl   pgtype.Text
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganiserID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Location,
		arg.Venue,
		arg.BannerUrl,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.IsOnline,
		arg.OnlineUrl,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :one
UPDATE "events"
SET
    "status"     = 'DELETED',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, deleteEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventById = `-- name: GetEventById :one
SELECT id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at FROM "events" WHERE "id" = $1
`

func (q *Queries) GetEventById(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at FROM "events" WHERE "slug" = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE "events"
SET
    "title"      = $2,
    "slug"       = $3,
    "description"= $4,
    "location"   = $5,
    "venue"      = $6,
    "banner_url" = $7,
    "starts_at"  = $8,
    "ends_at"    = $9,
    "is_online"  = $10,
    "online_url" = $11,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at
`

type UpdateEventParams struct {
	ID          pgtype.UUID
	Title       string
	Slug        string
	Description pgtype.Text
	Location    pgtype.Text
	Venue       pgtype.Text
	BannerUrl   pgtype.Text
	StartsAt    pgtype.Timestamp
	EndsAt      pgtype.Timestamp
	IsOnline    bool
	OnlineUrl   pgtype.Text
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Location,
		arg.Venue,
		arg.BannerUrl,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsOnline,
		arg.OnlineUrl,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganiserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Location,
		&i.Venue,
		&i.BannerUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
