// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events_public.sql

package repository

import (
	"context"
)

const publicGetPublishedEvents = `-- name: PublicGetPublishedEvents :many
SELECT id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at FROM "events"
WHERE "status" = 'PUBLISHED'
ORDER BY "starts_at" ASC
`

func (q *Queries) PublicGetPublishedEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, publicGetPublishedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.Venue,
			&i.BannerUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicGetUpcomingEvents = `-- name: PublicGetUpcomingEvents :many
SELECT id, organiser_id, title, slug, description, location, venue, banner_url, starts_at, ends_at, status, is_online, online_url, created_at, updated_at FROM "events"
WHERE "status" = 'PUBLISHED'
AND "starts_at" > NOW()
ORDER BY "starts_at" ASC
`

func (q *Queries) PublicGetUpcomingEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, publicGetUpcomingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganiserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Location,
			&i.Venue,
			&i.BannerUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
