// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventStatus string

const (
	EventStatusDRAFT     EventStatus = "DRAFT"
	EventStatusPUBLISHED EventStatus = "PUBLISHED"
	EventStatusCANCELLED EventStatus = "CANCELLED"
	EventStatusCOMPLETED EventStatus = "COMPLETED"
	EventStatusDELETED   EventStatus = "DELETED"
)

func (e *EventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventStatus(s)
	case string:
		*e = EventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EventStatus: %T", src)
	}
	return nil
}

type NullEventStatus struct {
	EventStatus EventStatus
	Valid       bool // Valid is true if EventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventStatus), nil
}

type OrderStatus string

const (
	OrderStatusPENDING   OrderStatus = "PENDING"
	OrderStatusPAID      OrderStatus = "PAID"
	OrderStatusFAILED    OrderStatus = "FAILED"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
	OrderStatusREFUNDED  OrderStatus = "REFUNDED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodMPESA PaymentMethod = "MPESA"
	PaymentMethodCARD  PaymentMethod = "CARD"
	PaymentMethodFREE  PaymentMethod = "FREE"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod
	Valid         bool // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type TicketTypeStatus string

const (
	TicketTypeStatusACTIVE  TicketTypeStatus = "ACTIVE"
	TicketTypeStatusDELETED TicketTypeStatus = "DELETED"
)

func (e *TicketTypeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketTypeStatus(s)
	case string:
		*e = TicketTypeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketTypeStatus: %T", src)
	}
	return nil
}

type NullTicketTypeStatus struct {
	TicketTypeStatus TicketTypeStatus
	Valid            bool // Valid is true if TicketTypeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketTypeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketTypeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketTypeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketTypeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketTypeStatus), nil
}

type UserRole string

const (
	UserRoleATTENDEE  UserRole = "ATTENDEE"
	UserRoleORGANISER UserRole = "ORGANISER"
	UserRoleADMIN     UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusACTIVE  UserStatus = "ACTIVE"
	UserStatusBANNED  UserStatus = "BANNED"
	UserStatusDELETED UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Event struct {
	ID          pgtype.UUID
	OrganiserID pgtype.UUID
	Title       string
	Slug        string
	Description pgtype.Text
	Location    pgtype.Text
	Venue       pgtype.Text
	BannerUrl   pgtype.Text
	StartsAt    pgtype.Timestamp
	EndsAt      pgtype.Timestamp
	Status      EventStatus
	IsOnline    bool
	OnlineUrl   pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Order struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	EventID       pgtype.UUID
	TicketTypeID  pgtype.UUID
	Quantity      int32
	UnitPrice     pgtype.Numeric
	TotalAmount   pgtype.Numeric
	Currency      string
	Status        OrderStatus
	PaymentMethod NullPaymentMethod
	PaymentRef    pgtype.Text
	QrCode        pgtype.Text
	CheckedIn     bool
	CheckedInAt   pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	UsedAt    pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type TicketType struct {
	ID           pgtype.UUID
	EventID      pgtype.UUID
	Name         string
	Status       TicketTypeStatus
	Description  pgtype.Text
	Price        int64
	Currency     string
	Quantity     int32
	QuantitySold int32
	IsFree       bool
	SaleStarts   pgtype.Timestamp
	SaleEnds     pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type User struct {
	ID         pgtype.UUID
	Name       string
	Email      string
	Password   string
	Role       UserRole
	IsVerified bool
	Status     UserStatus
	AvatarUrl  pgtype.Text
	BannedAt   pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
