// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInOrder = `-- name: CheckInOrder :one
UPDATE "orders"
SET
    "checked_in"    = TRUE,
    "checked_in_at" = NOW(),
    "updated_at"    = NOW()
WHERE "id" = $1
AND "checked_in" = FALSE
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

func (q *Queries) CheckInOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, checkInOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO "orders" (
    "user_id",
    "event_id",
    "ticket_type_id",
    "quantity",
    "unit_price",
    "total_amount",
    "currency",
    "status",
    "payment_method"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type CreateOrderParams struct {
	UserID        pgtype.UUID
	EventID       pgtype.UUID
	TicketTypeID  pgtype.UUID
	Quantity      int32
	UnitPrice     pgtype.Numeric
	TotalAmount   pgtype.Numeric
	Currency      string
	Status        OrderStatus
	PaymentMethod NullPaymentMethod
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.EventID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Currency,
		arg.Status,
		arg.PaymentMethod,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "orders" WHERE "id" = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getCheckedInOrders = `-- name: GetCheckedInOrders :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "event_id" = $1
AND "checked_in" = TRUE
ORDER BY "checked_in_at" ASC
`

func (q *Queries) GetCheckedInOrders(ctx context.Context, eventID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getCheckedInOrders, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders" WHERE "id" = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByPaymentRef = `-- name: GetOrderByPaymentRef :one
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "payment_ref" = $1
`

func (q *Queries) GetOrderByPaymentRef(ctx context.Context, paymentRef pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByPaymentRef, paymentRef)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByEvent = `-- name: GetOrdersByEvent :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "event_id" = $1
ORDER BY "created_at" DESC
`

func (q *Queries) GetOrdersByEvent(ctx context.Context, eventID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByEventAndStatus = `-- name: GetOrdersByEventAndStatus :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "event_id" = $1
AND "status" = $2
ORDER BY "created_at" DESC
`

type GetOrdersByEventAndStatusParams struct {
	EventID pgtype.UUID
	Status  OrderStatus
}

func (q *Queries) GetOrdersByEventAndStatus(ctx context.Context, arg GetOrdersByEventAndStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByEventAndStatus, arg.EventID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUser = `-- name: GetOrdersByUser :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "user_id" = $1
ORDER BY "created_at" DESC
`

func (q *Queries) GetOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPayment = `-- name: UpdateOrderPayment :one
UPDATE "orders"
SET
    "status"         = $2,
    "payment_method" = $3,
    "payment_ref"    = $4,
    "updated_at"     = NOW()
WHERE "id" = $1
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type UpdateOrderPaymentParams struct {
	ID            pgtype.UUID
	Status        OrderStatus
	PaymentMethod NullPaymentMethod
	PaymentRef    pgtype.Text
}

func (q *Queries) UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPayment,
		arg.ID,
		arg.Status,
		arg.PaymentMethod,
		arg.PaymentRef,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderQRCode = `-- name: UpdateOrderQRCode :one
UPDATE "orders"
SET
    "qr_code"    = $2,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type UpdateOrderQRCodeParams struct {
	ID     pgtype.UUID
	QrCode pgtype.Text
}

func (q *Queries) UpdateOrderQRCode(ctx context.Context, arg UpdateOrderQRCodeParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderQRCode, arg.ID, arg.QrCode)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE "orders"
SET
    "status"     = $2,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID
	Status OrderStatus
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
