// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders_organiser.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventCheckedInCount = `-- name: GetEventCheckedInCount :one
SELECT COUNT(*) AS checked_in
FROM orders
WHERE event_id = $1
AND checked_in = TRUE
`

func (q *Queries) GetEventCheckedInCount(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEventCheckedInCount, eventID)
	var checked_in int64
	err := row.Scan(&checked_in)
	return checked_in, err
}

const getEventOrders = `-- name: GetEventOrders :many
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
FROM orders
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetEventOrders(ctx context.Context, eventID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getEventOrders, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.PaymentRef,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventOrdersCount = `-- name: GetEventOrdersCount :one
SELECT COUNT(*) AS total_orders
FROM orders
WHERE event_id = $1
`

func (q *Queries) GetEventOrdersCount(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEventOrdersCount, eventID)
	var total_orders int64
	err := row.Scan(&total_orders)
	return total_orders, err
}

const getEventRevenue = `-- name: GetEventRevenue :one
SELECT COALESCE(SUM(total_amount), 0) AS revenue
FROM orders
WHERE event_id = $1
AND status = 'PAID'
`

func (q *Queries) GetEventRevenue(ctx context.Context, eventID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getEventRevenue, eventID)
	var revenue interface{}
	err := row.Scan(&revenue)
	return revenue, err
}
