// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "orders" (
    "user_id",
    "event_id",
    "ticket_type_id",
    "quantity",
    "unit_price",
    "total_amount",
    "currency",
    "status",
    "payment_method"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type CreateOrderParams struct {
	UserID        pgtype.UUID
	EventID       pgtype.UUID
	TicketTypeID  pgtype.UUID
	Quantity      int32
	UnitPrice     pgtype.Numeric
	TotalAmount   pgtype.Numeric
	Currency      string
	Status        OrderStatus
	PaymentMethod NullPaymentMethod
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.EventID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Currency,
		arg.Status,
		arg.PaymentMethod,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "orders" WHERE "id" = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders" WHERE "id" = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByUser = `-- name: GetOrdersByUser :many
SELECT
    o.id,
    o.quantity,
    o.status,
    o.qr_code,
    o.checked_in,
    o.checked_in_at,
    o.created_at,
    e.title       AS event_title,
    e.slug        AS event_slug,
    e.starts_at   AS event_starts_at,
    e.ends_at     AS event_ends_at,
    e.location    AS event_location,
    e.venue       AS event_venue,
    e.is_online   AS event_is_online,
    e.online_url  AS event_online_url,
    e.banner_url  AS event_banner_url,
    tt.name       AS ticket_type_name,
    tt.price      AS ticket_type_price
FROM "orders" o
JOIN "events" e       ON e.id = o.event_id
JOIN "ticket_types" tt ON tt.id = o.ticket_type_id
WHERE o.user_id = $1
AND o.status = 'PAID'
ORDER BY e.starts_at ASC
`

type GetOrdersByUserRow struct {
	ID              pgtype.UUID
	Quantity        int32
	Status          OrderStatus
	QrCode          pgtype.Text
	CheckedIn       bool
	CheckedInAt     pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	EventTitle      string
	EventSlug       string
	EventStartsAt   pgtype.Timestamp
	EventEndsAt     pgtype.Timestamp
	EventLocation   pgtype.Text
	EventVenue      pgtype.Text
	EventIsOnline   bool
	EventOnlineUrl  pgtype.Text
	EventBannerUrl  pgtype.Text
	TicketTypeName  string
	TicketTypePrice int64
}

func (q *Queries) GetOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]GetOrdersByUserRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserRow
	for rows.Next() {
		var i GetOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Status,
			&i.QrCode,
			&i.CheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.EventTitle,
			&i.EventSlug,
			&i.EventStartsAt,
			&i.EventEndsAt,
			&i.EventLocation,
			&i.EventVenue,
			&i.EventIsOnline,
			&i.EventOnlineUrl,
			&i.EventBannerUrl,
			&i.TicketTypeName,
			&i.TicketTypePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
