// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderByPaymentRef = `-- name: GetOrderByPaymentRef :one
SELECT id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at FROM "orders"
WHERE "payment_ref" = $1
`

func (q *Queries) GetOrderByPaymentRef(ctx context.Context, paymentRef pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByPaymentRef, paymentRef)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderPayment = `-- name: UpdateOrderPayment :one
UPDATE "orders"
SET
    "status"         = $2,
    "payment_method" = $3,
    "payment_ref"    = $4,
    "updated_at"     = NOW()
WHERE "id" = $1
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type UpdateOrderPaymentParams struct {
	ID            pgtype.UUID
	Status        OrderStatus
	PaymentMethod NullPaymentMethod
	PaymentRef    pgtype.Text
}

func (q *Queries) UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPayment,
		arg.ID,
		arg.Status,
		arg.PaymentMethod,
		arg.PaymentRef,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderQRCode = `-- name: UpdateOrderQRCode :one
UPDATE "orders"
SET
    "qr_code"    = $2,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type UpdateOrderQRCodeParams struct {
	ID     pgtype.UUID
	QrCode pgtype.Text
}

func (q *Queries) UpdateOrderQRCode(ctx context.Context, arg UpdateOrderQRCodeParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderQRCode, arg.ID, arg.QrCode)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE "orders"
SET
    "status"     = $2,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, user_id, event_id, ticket_type_id, quantity, unit_price, total_amount, currency, status, payment_method, payment_ref, qr_code, checked_in, checked_in_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID
	Status OrderStatus
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentRef,
		&i.QrCode,
		&i.CheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
