// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket_types.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO "ticket_types" (
    "event_id",
    "name",
    "description",
    "price",
    "currency",
    "quantity",
    "is_free",
    "sale_starts",
    "sale_ends"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, event_id, name, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at
`

type CreateTicketTypeParams struct {
	EventID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Price       int64
	Currency    string
	Quantity    int32
	IsFree      bool
	SaleStarts  pgtype.Timestamp
	SaleEnds    pgtype.Timestamp
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.Quantity,
		arg.IsFree,
		arg.SaleStarts,
		arg.SaleEnds,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Quantity,
		&i.QuantitySold,
		&i.IsFree,
		&i.SaleStarts,
		&i.SaleEnds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementQuantitySold = `-- name: DecrementQuantitySold :one
UPDATE ticket_types
SET
    quantity_sold = quantity_sold - $2,
    updated_at = NOW()
WHERE id = $1
  AND quantity_sold >= $2
RETURNING id, event_id, name, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at
`

type DecrementQuantitySoldParams struct {
	ID           pgtype.UUID
	QuantitySold int32
}

func (q *Queries) DecrementQuantitySold(ctx context.Context, arg DecrementQuantitySoldParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, decrementQuantitySold, arg.ID, arg.QuantitySold)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Quantity,
		&i.QuantitySold,
		&i.IsFree,
		&i.SaleStarts,
		&i.SaleEnds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicketType = `-- name: DeleteTicketType :exec
DELETE FROM "ticket_types" WHERE "id" = $1
`

func (q *Queries) DeleteTicketType(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTicketType, id)
	return err
}

const getAvailableTicketTypes = `-- name: GetAvailableTicketTypes :many
SELECT tt.id, tt.event_id, tt.name, tt.description, tt.price, tt.currency, tt.quantity, tt.quantity_sold, tt.is_free, tt.sale_starts, tt.sale_ends, tt.created_at, tt.updated_at
FROM ticket_types tt
JOIN events e ON e.id = tt.event_id
WHERE tt.event_id = $1
  AND tt.quantity_sold < tt.quantity
  AND (tt.sale_starts IS NULL OR tt.sale_starts <= NOW())
  AND (tt.sale_ends IS NULL OR tt.sale_ends >= NOW())
  AND e.starts_at > NOW()
ORDER BY tt.price ASC
`

func (q *Queries) GetAvailableTicketTypes(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, getAvailableTicketTypes, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Quantity,
			&i.QuantitySold,
			&i.IsFree,
			&i.SaleStarts,
			&i.SaleEnds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketTypeById = `-- name: GetTicketTypeById :one
SELECT id, event_id, name, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at FROM "ticket_types" WHERE "id" = $1
`

func (q *Queries) GetTicketTypeById(ctx context.Context, id pgtype.UUID) (TicketType, error) {
	row := q.db.QueryRow(ctx, getTicketTypeById, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Quantity,
		&i.QuantitySold,
		&i.IsFree,
		&i.SaleStarts,
		&i.SaleEnds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTypesByEvent = `-- name: GetTicketTypesByEvent :many
SELECT id, event_id, name, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at FROM "ticket_types"
WHERE "event_id" = $1
ORDER BY "price" ASC
`

func (q *Queries) GetTicketTypesByEvent(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, getTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Quantity,
			&i.QuantitySold,
			&i.IsFree,
			&i.SaleStarts,
			&i.SaleEnds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementQuantitySold = `-- name: IncrementQuantitySold :one
UPDATE ticket_types
SET
    quantity_sold = quantity_sold + $2,
    updated_at = NOW()
WHERE id = $1
  AND quantity_sold + $2 <= quantity
RETURNING id, event_id, name, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at
`

type IncrementQuantitySoldParams struct {
	ID           pgtype.UUID
	QuantitySold int32
}

func (q *Queries) IncrementQuantitySold(ctx context.Context, arg IncrementQuantitySoldParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, incrementQuantitySold, arg.ID, arg.QuantitySold)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Quantity,
		&i.QuantitySold,
		&i.IsFree,
		&i.SaleStarts,
		&i.SaleEnds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketType = `-- name: UpdateTicketType :one
UPDATE "ticket_types"
SET
    "name"        = $2,
    "description" = $3,
    "price"       = $4,
    "currency"    = $5,
    "quantity"    = $6,
    "is_free"     = $7,
    "sale_starts" = $8,
    "sale_ends"   = $9,
    "updated_at"  = NOW()
WHERE "id" = $1
RETURNING id, event_id, name, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at
`

type UpdateTicketTypeParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Price       int64
	Currency    string
	Quantity    int32
	IsFree      bool
	SaleStarts  pgtype.Timestamp
	SaleEnds    pgtype.Timestamp
}

func (q *Queries) UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, updateTicketType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.Quantity,
		arg.IsFree,
		arg.SaleStarts,
		arg.SaleEnds,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Quantity,
		&i.QuantitySold,
		&i.IsFree,
		&i.SaleStarts,
		&i.SaleEnds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
