// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_types_public.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const publicGetAvailableTicketTypes = `-- name: PublicGetAvailableTicketTypes :many
SELECT tt.id, tt.event_id, tt.name, tt.status, tt.description, tt.price, tt.currency, tt.quantity, tt.quantity_sold, tt.is_free, tt.sale_starts, tt.sale_ends, tt.created_at, tt.updated_at
FROM ticket_types tt
JOIN events e ON e.id = tt.event_id
WHERE tt.event_id = $1
  AND tt.quantity_sold < tt.quantity
  AND (tt.sale_starts IS NULL OR tt.sale_starts <= NOW())
  AND (tt.sale_ends IS NULL OR tt.sale_ends >= NOW())
  AND e.starts_at > NOW()
ORDER BY tt.price ASC
`

func (q *Queries) PublicGetAvailableTicketTypes(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, publicGetAvailableTicketTypes, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Status,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Quantity,
			&i.QuantitySold,
			&i.IsFree,
			&i.SaleStarts,
			&i.SaleEnds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
