// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_types_inventory.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementQuantitySold = `-- name: DecrementQuantitySold :one
UPDATE ticket_types
SET
    quantity_sold = quantity_sold - $2,
    updated_at = NOW()
WHERE id = $1
  AND quantity_sold >= $2
RETURNING id
`

type DecrementQuantitySoldParams struct {
	ID           pgtype.UUID
	QuantitySold int32
}

func (q *Queries) DecrementQuantitySold(ctx context.Context, arg DecrementQuantitySoldParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, decrementQuantitySold, arg.ID, arg.QuantitySold)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const incrementQuantitySold = `-- name: IncrementQuantitySold :one
UPDATE ticket_types
SET
    quantity_sold = quantity_sold + $2,
    updated_at = NOW()
WHERE id = $1
  AND quantity_sold + $2 <= quantity
RETURNING id
`

type IncrementQuantitySoldParams struct {
	ID           pgtype.UUID
	QuantitySold int32
}

func (q *Queries) IncrementQuantitySold(ctx context.Context, arg IncrementQuantitySoldParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, incrementQuantitySold, arg.ID, arg.QuantitySold)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
