// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_types_organiser.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const organiserGetTicketTypesByEvent = `-- name: OrganiserGetTicketTypesByEvent :many
SELECT id, event_id, name, status, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at FROM "ticket_types"
WHERE "event_id" = $1
ORDER BY "price" ASC
`

func (q *Queries) OrganiserGetTicketTypesByEvent(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, organiserGetTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Status,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Quantity,
			&i.QuantitySold,
			&i.IsFree,
			&i.SaleStarts,
			&i.SaleEnds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
