// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_types_organiser.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const organiserGetTicketTypeSalesByEvent = `-- name: OrganiserGetTicketTypeSalesByEvent :many
SELECT
    id,
    name,
    price,
    quantity,
    quantity_sold,
    (quantity_sold * price) AS revenue
FROM ticket_types
WHERE event_id = $1
ORDER BY price ASC
`

type OrganiserGetTicketTypeSalesByEventRow struct {
	ID           pgtype.UUID
	Name         string
	Price        int64
	Quantity     int32
	QuantitySold int32
	Revenue      int32
}

func (q *Queries) OrganiserGetTicketTypeSalesByEvent(ctx context.Context, eventID pgtype.UUID) ([]OrganiserGetTicketTypeSalesByEventRow, error) {
	rows, err := q.db.Query(ctx, organiserGetTicketTypeSalesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganiserGetTicketTypeSalesByEventRow
	for rows.Next() {
		var i OrganiserGetTicketTypeSalesByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.QuantitySold,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organiserGetTicketTypesByEvent = `-- name: OrganiserGetTicketTypesByEvent :many
SELECT id, event_id, name, status, description, price, currency, quantity, quantity_sold, is_free, sale_starts, sale_ends, created_at, updated_at FROM "ticket_types"
WHERE "event_id" = $1
ORDER BY "price" ASC
`

func (q *Queries) OrganiserGetTicketTypesByEvent(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, organiserGetTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Status,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Quantity,
			&i.QuantitySold,
			&i.IsFree,
			&i.SaleStarts,
			&i.SaleEnds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organiserGetTotalTicketsSold = `-- name: OrganiserGetTotalTicketsSold :one
SELECT COALESCE(SUM("quantity_sold"), 0)::BIGINT AS total_sold
FROM "ticket_types"
WHERE "event_id" = $1
`

func (q *Queries) OrganiserGetTotalTicketsSold(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, organiserGetTotalTicketsSold, eventID)
	var total_sold int64
	err := row.Scan(&total_sold)
	return total_sold, err
}
