// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_types_public.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const publicGetAvailableTicketTypes = `-- name: PublicGetAvailableTicketTypes :many
SELECT
    tt.id,
    tt.event_id,
    tt.name,
    tt.description,
    tt.price,
    tt.currency,
    tt.is_free
FROM ticket_types tt
JOIN events e ON e.id = tt.event_id
WHERE tt.event_id = $1
  AND tt.status = 'ACTIVE'
  AND tt.quantity_sold < tt.quantity
  AND (tt.sale_starts IS NULL OR tt.sale_starts <= NOW())
  AND (tt.sale_ends IS NULL OR tt.sale_ends >= NOW())
  AND e.starts_at > NOW()
ORDER BY tt.price ASC
`

type PublicGetAvailableTicketTypesRow struct {
	ID          pgtype.UUID
	EventID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Price       int64
	Currency    string
	IsFree      bool
}

func (q *Queries) PublicGetAvailableTicketTypes(ctx context.Context, eventID pgtype.UUID) ([]PublicGetAvailableTicketTypesRow, error) {
	rows, err := q.db.Query(ctx, publicGetAvailableTicketTypes, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicGetAvailableTicketTypesRow
	for rows.Next() {
		var i PublicGetAvailableTicketTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.IsFree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
