// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" (
    "name",
    "email",
    "password",
    "role",
    "is_verified"
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

type CreateUserParams struct {
	Name       string
	Email      string
	Password   string
	Role       UserRole
	IsVerified bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.IsVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE "users"
SET
    "status"     = 'DELETED',
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at FROM "users" WHERE "email" = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at FROM "users" WHERE "id" = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE "users"
SET
    "avatar_url" = $2,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID
	AvatarUrl pgtype.Text
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE "users"
SET
    "password"   = $2,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID       pgtype.UUID
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE "users"
SET
    "name"       = $2,
    "email"      = $3,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, name, email, password, role, is_verified, status, avatar_url, banned_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID    pgtype.UUID
	Name  string
	Email string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsVerified,
		&i.Status,
		&i.AvatarUrl,
		&i.BannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
